version: "3.9"
services:
  salesapp:
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"