spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/sales'
    username: postgres
    password: 12314
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
mybatis:
  type-aliases-package: com.example.salesrecord.typehandler
  mapper-locations: classpath:mapper/*.xml